[package]
name = "mimium-lang"
version = "0.0.1"
license = "MPL 2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# [lib]


[dependencies]

chumsky = "0.9"
ariadne = "0.1.5"
clap = { version = "4.5.7", features = ["derive"] }
