[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Extra static files to include in each App (path relative to this Cargo.toml's dir)
include = ["./lib/", "./examples/"]
# The archive format to use for non-windows builds (defaults .tar.xz)
unix-archive = ".zip"
# The archive format to use for windows builds (defaults .zip)
windows-archive = ".zip"
# Path that installers should place binaries in
install-path = "~/.mimium"
# Whether to install an updater program
install-updater = false

[dist.dependencies.apt]
libasound2-dev = "*"

[dist.github-custom-runners]
x86_64-unknown-linux-gnu = "ubuntu-latest"
