[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.25.1"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "msi", "powershell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = [
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
]

include = ["./mimium-cli/lib/", ".Readme.md", "./mimium_logo_slant.svg"]

unix-archive = ".zip"
windows-archive = ".zip"

[dist.dependencies.apt]
libasound2-dev = "*"

[dist.github-custom-runners]
x86_64-unknown-linux-gnu = "ubuntu-latest"
