[package]
name = "mimium-fmt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty = "0.12.0"
mimium-lang = { path = "../mimium-lang" }
clap = { version = "4.4.2", features = ["derive"] }
