use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn generate_fileloader_cjs(source: &str) -> String {
    let export_block = source
        .rsplit_once("export {\n")
        .expect("fileloader.mjs must end with an export block");
    let export_names = export_block
        .1
        .trim_end()
        .strip_suffix("};")
        .expect("fileloader.mjs export block must end with '};'")
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .map(|line| line.trim_end_matches(','))
        .collect::<Vec<_>>();

    let mut generated =
        String::from("// This file is generated by build.rs from src/utils/fileloader.mjs.\n");
    generated.push_str("// Do not edit this file directly.\n\n");
    generated.push_str(export_block.0);
    generated.push_str("module.exports = {\n");
    export_names
        .iter()
        .for_each(|name| generated.push_str(&format!("  {name},\n")));
    generated.push_str("};\n");
    generated
}

fn sync_fileloader_cjs(manifest_dir: &Path) {
    let fileloader_mjs = manifest_dir.join("src/utils/fileloader.mjs");
    let fileloader_cjs = manifest_dir.join("src/utils/fileloader.cjs");
    println!("cargo:rerun-if-changed={}", fileloader_mjs.display());

    let source = fs::read_to_string(&fileloader_mjs).expect("Failed to read fileloader.mjs");
    let generated = generate_fileloader_cjs(&source);
    let existing = fs::read_to_string(&fileloader_cjs).ok();
    if existing.as_deref() != Some(generated.as_str()) {
        fs::write(&fileloader_cjs, generated).expect("Failed to write fileloader.cjs");
    }
}

fn main() {
    println!("cargo:rustc-env=TEST_ROOT={}", env!("CARGO_MANIFEST_DIR"));
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    sync_fileloader_cjs(&manifest_dir);

    // When building tests (not on wasm32), ensure plugin cdylibs are built
    let target = env::var("TARGET").unwrap_or_default();
    let profile = env::var("PROFILE").unwrap_or_default();

    // Only build plugins for native tests (not for wasm32 or when building lib only)
    if !target.contains("wasm32") && profile == "debug" {
        // Check if we're building tests by looking for CARGO_CFG_TEST or checking features
        let building_tests =
            env::var("CARGO_CFG_TEST").is_ok() || env::var("CARGO_PRIMARY_PACKAGE").is_ok();

        if building_tests {
            println!("cargo:warning=Building plugin cdylibs for integration tests...");

            // Get the workspace root
            let workspace_root = manifest_dir
                .parent()
                .and_then(|p| p.parent())
                .and_then(|p| p.parent())
                .expect("Failed to find workspace root");

            // Build mimium-symphonia as cdylib
            let status = Command::new("cargo")
                .arg("build")
                .arg("--package")
                .arg("mimium-symphonia")
                .arg("--lib")
                .current_dir(workspace_root)
                .status();

            match status {
                Ok(status) if status.success() => {
                    println!("cargo:warning=Successfully built mimium-symphonia plugin");
                }
                Ok(status) => {
                    println!(
                        "cargo:warning=Failed to build mimium-symphonia: exit code {:?}",
                        status.code()
                    );
                }
                Err(e) => {
                    println!("cargo:warning=Failed to execute cargo build: {}", e);
                }
            }

            // Tell cargo to rerun if the plugin sources change
            println!("cargo:rerun-if-changed=../plugins/mimium-symphonia/src");
        }
    }
}
