// Append this file after Rust generated by `mimium-cli --emit-rust`.
// Example:
// cargo run --bin mimium-cli --release examples/sinewave.mmm --emit-rust > tmp/manual_sinewave.rs
// cat tmp/rust_codegen_manual_main.rs >> tmp/manual_sinewave.rs
// rustc --edition=2024 tmp/manual_sinewave.rs -o tmp/manual_sinewave
// ./tmp/manual_sinewave

struct TestHost {
    now: f64,
    sample_rate: f64,
}

impl MimiumHost for TestHost {
    fn call_ext(
        &mut self,
        name: &str,
        _args: &[Word],
        _ret_words: usize,
    ) -> Result<Vec<Word>, String> {
        Err(format!("unexpected external call: {}", name))
    }

    fn current_time(&mut self) -> f64 {
        let value = self.now;
        self.now += 1.0;
        value
    }

    fn sample_rate(&mut self) -> f64 {
        self.sample_rate
    }
}

fn main() {
    let host = TestHost {
        now: 0.0,
        sample_rate: 48_000.0,
    };
    let mut program = MimiumProgram::with_host(host);

    // Uncomment when the generated source defines `call_main` and needs global initialization.
    // program.call_main().unwrap();

    for input in [0.0f64, 0.0, 0.0, 0.0] {
        let output = program.call_dsp(&[f64_to_word(input)]).unwrap();
        for word in output {
            println!("{:.12}", word_to_f64(word));
        }
    }
}