[package]
name = "mimium-guitools"
version = "2.0.0-alpha-1"
license = "MPL 2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# [lib]


[dependencies]
egui = "0.29.1"
egui_plot = "0.29.0"
mimium-lang = {path = "../mimium-lang"}
