[package]
name = "mimium-cli"
version = "2.0.0-alpha-1"
license = "MPL 2.0"
edition = "2021"
repository = "https://github.com/tomoyanonymous/mimium-rs/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# [lib]


[dependencies]

clap = { version = "4.5.7", features = ["derive"] }
log = "0.4.22"

mimium-lang = { path = "../mimium-lang" }
mimium-audiodriver = { path = "../mimium-audiodriver" }
mimium-midi = { path = "../mimium-midi" }
mimium-symphonia = { path = "../mimium-symphonia" }
mimium-scheduler = { path = "../mimium-scheduler" }
colog = "1.3.0"
