name: CI

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cargo_test:
    name: "cargo test (OS: ${{ matrix.config.os }}"
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest }
          - { os: ubuntu-latest }
          # - { os: macOS-latest }
          # - { os: windows-latest }

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - name: Install system requirements for Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt update -y
          sudo apt install -y libasound2-dev
      
      - run: cargo test
