name: Test for Web

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cargo_test_setup:
    name: "setup test for web"
    runs-on: ubuntu-latest 
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
  integration_test:
    needs: cargo_test_setup
    name: "mimium-lang test for web"
    runs-on: ubuntu-latest 
    strategy:
      fail-fast: false
    steps:
      - run: wasm-pack test --node
        working-directory: mimium-test
  lang_unit_test:
    needs: cargo_test_setup
    name: "mimium-lang test for web"
    runs-on: ubuntu-latest 
    strategy:
      fail-fast: false
    steps:
      - run: wasm-pack test --node
        working-directory: mimium-lang
